version: '3'

services:
  db:
    build:
      context: ./
      dockerfile: smart-db.Dockerfile
    image: ${NAME}-db:${TAG}
    container_name: ${NAME}-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: smart.2023
    volumes:
      - ../:/app
      - ./mysql/var/lib/mysql:/var/lib/mysql
    ulimits:
      nofile:
        soft: 500000
        hard: 500000
    security_opt:
       - seccomp:unconfined
    expose:
      - 3306
      - 33060
    ports:
      - 3306:3306
      - 33060:33060

  smart:
    build:
      context: ./
      dockerfile: smart.Dockerfile
    image: ${NAME}-app:${TAG}
    container_name: ${NAME}-app
    restart: always
    volumes:
      - ../:/app
      - ./php/var/run/php-fpm:/var/run/php-fpm
      - ./php/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/usr/local/etc/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./php/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    expose:
      - 9000

  nginx:
    build:
      context: ./
      dockerfile: smart-nginx.Dockerfile
    image: ${NAME}-nginx:${TAG}
    container_name: ${NAME}-nginx
    restart: always
    volumes:
      - ./nginx/var/www/html:/var/www/html
      - ./php/var/run/php-fpm:/var/run/php-fpm
      - ./nginx/etc/nginx/conf:/etc/nginx/conf
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - smart
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    
  api:
    build:
      context: ./
      dockerfile: smart-api.Dockerfile
    image: ${NAME}-api:${TAG}
    container_name: ${NAME}-api
    restart: always
    volumes:
      - ../:/app
      - ./php/var/run/php-fpm:/var/run/php-fpm
      - ./nginx/etc/nginx/api.conf:/etc/nginx/nginx.conf
    depends_on:
      - smart
    expose:
      - 80
      - 8080
    ports:
      - 8081:80

  # web:
  #   build:
  #     context: ./
  #     dockerfile: smart-web.Dockerfile
  #   image: ${NAME}-web:${TAG}
  #   container_name: ${NAME}-web
  #   restart: always
  #   volumes:
  #     - ../:/app
  #     - ./php/var/run/php-fpm:/var/run/php-fpm
  #     - ./nginx/etc/nginx/web.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - smart
  #   expose:
  #     - 80
  #     - 8080
  #   ports:
  #     - 8080:80

  storage:
    build:
      context: ./
      dockerfile: smart-storage.Dockerfile
    image: ${NAME}-storage:${TAG}
    container_name: ${NAME}-storage
    restart: always
    volumes:
      - ../:/app
      - ./nginx/etc/nginx/storage.conf:/etc/nginx/nginx.conf
    depends_on:
      - smart
    expose:
      - 80
      - 8080
    ports:
      - 8082:80